### ISSUE TITLE
Pipenv Won't Install Version 1.0.0 of Okta

### ISSUE THREAD

**Issue by estein9825** [okta/okta-sdk-python#124]
When trying to run `pipenv install okta` to install version 1.0.0 on Python 3.8 I get:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pipenv/resolver.py", line 807, in <module>
    main()
  File "/usr/local/lib/python3.8/site-packages/pipenv/resolver.py", line 802, in main
    _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system, parsed.write,
  File "/usr/local/lib/python3.8/site-packages/pipenv/resolver.py", line 785, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages)
  File "/usr/local/lib/python3.8/site-packages/pipenv/resolver.py", line 746, in resolve_packages
    results, resolver = resolve(
  File "/usr/local/lib/python3.8/site-packages/pipenv/resolver.py", line 728, in resolve
    return resolve_deps(
  File "/usr/local/lib/python3.8/site-packages/pipenv/utils.py", line 1378, in resolve_deps
    results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
  File "/usr/local/lib/python3.8/site-packages/pipenv/utils.py", line 1095, in actually_resolve_deps
    resolver.resolve_constraints()
  File "/usr/local/lib/python3.8/site-packages/pipenv/utils.py", line 847, in resolve_constraints
    marker = marker_from_specifier(candidate.requires_python)
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 719, in marker_from_specifier
    for marker_segment in cleanup_pyspecs(spec):
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 288, in cleanup_pyspecs
    for op_and_version_type, versions in _group_by_op(tuple(specs)):
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 203, in _group_by_op
    specs = [_get_specs(x) for x in list(specs)]
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 203, in <listcomp>
    specs = [_get_specs(x) for x in list(specs)]
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 187, in _get_specs
    for spec in set(specset):
TypeError: 'LegacySpecifier' object is not iterable
```

Running it with `-v` points to an issue when it's attempting to generate the hashes for Okta:

```
Generating hashes:
  flask-pyoidc
  cffi
  pluggy
  pyasn1-modules
  pyasn1
  ecdsa
  jsonschema
  attrs
  future
  flatdict
  httplib2
  flask-restful-swagger-2
  webargs
  aniso8601
  pytest-recording
  flask-swagger-ui
  pyparsing
  certifi
  iniconfig
  pycryptodome
  oic
  pyfakefs
  urllib3
  flake8
  oauth2client
  multidict
  flask
  requests
  importlib-resources
  py-healthcheck
  pycodestyle
  flask-smorest
  pytest-asyncio
  pycparser
  pyrsistent
  safrs
  packaging
  vcrpy
  pymysql
  mccabe
  pytest-mock
  toml
  mako
  markupsafe
  pytest
  click
  pydash
  rsa
  pytz
  itsdangerous
  wrapt
  beaker
  flask-cors
  pyjwt
  simplejson
  defusedxml
  py
  xmltodict
  chardet
  flask-oidc
  flask-caching
  cryptography
  pyflakes
  idna
  typing-extensions
  flask-restful
  mistune
  werkzeug
  pyjwkest
  marshmallow
  aiohttp
  apispec
  six
  sqlalchemy
  pyyaml
  jinja2
  asyncio
  pycryptodomex
  async-timeout
  flasgger
  pymongo
  flask-sqlalchemy
  okta
  python-jose
  inflect
  yarl
  aenum
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pipenv/resolver.py", line 807, in <module>
    main()
  File "/usr/local/lib/python3.8/site-packages/pipenv/resolver.py", line 802, in main
    _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system, parsed.write,
  File "/usr/local/lib/python3.8/site-packages/pipenv/resolver.py", line 785, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages)
  File "/usr/local/lib/python3.8/site-packages/pipenv/resolver.py", line 746, in resolve_packages
    results, resolver = resolve(
  File "/usr/local/lib/python3.8/site-packages/pipenv/resolver.py", line 728, in resolve
    return resolve_deps(
  File "/usr/local/lib/python3.8/site-packages/pipenv/utils.py", line 1378, in resolve_deps
    results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
  File "/usr/local/lib/python3.8/site-packages/pipenv/utils.py", line 1095, in actually_resolve_deps
    resolver.resolve_constraints()
  File "/usr/local/lib/python3.8/site-packages/pipenv/utils.py", line 847, in resolve_constraints
    marker = marker_from_specifier(candidate.requires_python)
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 719, in marker_from_specifier
    for marker_segment in cleanup_pyspecs(spec):
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 288, in cleanup_pyspecs
    for op_and_version_type, versions in _group_by_op(tuple(specs)):
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 203, in _group_by_op
    specs = [_get_specs(x) for x in list(specs)]
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 203, in <listcomp>
    specs = [_get_specs(x) for x in list(specs)]
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 187, in _get_specs
    for spec in set(specset):
TypeError: 'LegacySpecifier' object is not iterable
```

I am able to install version `0.0.4` without issues

**Comment by bretterer** [comment]
Thanks for the report!  Were investigating now

**Comment by bretterer** [comment]
@estein9825, We have updated the package to version 1.0.1 

Could you please try to re-install okta through pip and try again?

**Comment by estein9825** [comment]
Same issue
```
✘ Locking Failed! 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pipenv/resolver.py", line 807, in <module>
    main()
  File "/usr/local/lib/python3.8/site-packages/pipenv/resolver.py", line 802, in main
    _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system, parsed.write,
  File "/usr/local/lib/python3.8/site-packages/pipenv/resolver.py", line 785, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages)
  File "/usr/local/lib/python3.8/site-packages/pipenv/resolver.py", line 746, in resolve_packages
    results, resolver = resolve(
  File "/usr/local/lib/python3.8/site-packages/pipenv/resolver.py", line 728, in resolve
    return resolve_deps(
  File "/usr/local/lib/python3.8/site-packages/pipenv/utils.py", line 1378, in resolve_deps
    results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
  File "/usr/local/lib/python3.8/site-packages/pipenv/utils.py", line 1095, in actually_resolve_deps
    resolver.resolve_constraints()
  File "/usr/local/lib/python3.8/site-packages/pipenv/utils.py", line 847, in resolve_constraints
    marker = marker_from_specifier(candidate.requires_python)
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 719, in marker_from_specifier
    for marker_segment in cleanup_pyspecs(spec):
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 288, in cleanup_pyspecs
    for op_and_version_type, versions in _group_by_op(tuple(specs)):
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 203, in _group_by_op
    specs = [_get_specs(x) for x in list(specs)]
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 203, in <listcomp>
    specs = [_get_specs(x) for x in list(specs)]
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/requirementslib/models/markers.py", line 187, in _get_specs
    for spec in set(specset):
TypeError: 'LegacySpecifier' object is not iterable
```

**Comment by gabrielsroka** [comment]
@estein9825 i had to
```sh
pip uninstall okta
pip install okta
```
but then it worked for me. (note, i'm not using pipenv, just pip)

**Comment by bretterer** [comment]
Glad that worked.  

So, are you not using pipenv anymore?  The initial issue was pipenv wouldn't install okta.  Is that still an issue?

**Comment by estein9825** [comment]
@bretterer yeah no idea about that other person. But to answer your question a pipenv uninstall/reinstall did not help. Have you tried with pipenv? I’m using 2020.8.13

**Comment by bretterer** [comment]
@estein9825  I think we may have found the bug here.  Our `setup.py` file had `python_requires=">=3.6'",` which contains a rogue `'`.  I am working on getting a fix published as 1.0.2 and will update here when it is released

**Comment by bretterer** [comment]
@estein9825 we just released version 1.0.2 of the SDK which should fix the bug for `pipenv` installs... could you please try to see if its resolved for you now?

**Comment by estein9825** [comment]
@bretterer install was successful this time.

**Comment by bretterer** [comment]
Awesome to hear @estein9825.  Sorry for the troubles here.

If there are any other issues, please let us know!
