### ISSUE TITLE
AttributeError when retrieving paginated logs 

### ISSUE THREAD

**Issue by DREW1990** [okta/okta-sdk-python#135]
Hello I'm running into an error when using pagination with `client.gets_logs()`.

Here is my code:
```
#!/usr/bin/env python3.7

from okta.client import Client as OktaClient
from datetime import datetime, timedelta
import asyncio

# Okta config
okta_config = {
    'orgUrl': 'https://company.okta.com',
    'token': 'redacted'
}


async def get_okta_logs():
    logs = []
    client = OktaClient(okta_config)
    params = {
        'filter': 'eventType eq "user.account.lock"',
        'since': (datetime.now() - timedelta(7)).isoformat()[:-3] + 'Z',
        'until': datetime.now().isoformat()[:-3] + 'Z',
        'limit': '1'
    }

    events, response, error = await client.get_logs(query_params=params)
    for event in events:
        logs.append(event)
    if response.has_next():  # Returns True
        events, error = await response.next()
        for event in events:
            logs.append(event)

    if error:
        print(f'Okta API Error: {error}')

    print(logs)
```

The error I receive:
```
Traceback (most recent call last):
  File "okta_logs.py", line 40, in <module>
    asyncio.run(get_okta_logs())
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "okta_logs.py", line 30, in get_okta_logs
    events, error = await response.next()
  File "/usr/local/lib/python3.8/site-packages/okta/api_response.py", line 129, in next
    result.append(self._type(item))
  File "/usr/local/lib/python3.8/site-packages/okta/models/log_event.py", line 70, in __init__
    self.authentication_context = log_authentication_context.LogAuthenticationContext(
  File "/usr/local/lib/python3.8/site-packages/okta/models/log_authentication_context.py", line 48, in __init__
    config["authenticationProvider"].upper()
AttributeError: 'NoneType' object has no attribute 'upper'
```

My code has no issues receiving the first page, however when I use `response.next()` I keep seeing the attribute error.

**Comment by serhiibuniak-okta** [comment]
@DREW1990 thank you for this detailed description, problematic piece of code is located, working on solution.

**Comment by serhiibuniak-okta** [comment]
@DREW1990 Please, try install the latest version of okta

**Comment by DREW1990** [comment]
> @DREW1990 Please, try install the latest version of okta

@serhiibuniak-okta awesome, its working now! Thanks for the help! Any chance the latest version can be installed through pip soon?

**Comment by serhiibuniak-okta** [comment]
@DREW1990 Yes, we'll upload new package to pypi soon, I believe, on Monday

**Comment by serhiibuniak-okta** [comment]
@DREW1990 v1.0.4 is ready

**Comment by DREW1990** [comment]
Verified v1.0.4 is working! Thanks!
