### ISSUE TITLE
asyncio conflict with python 3.8?

### ISSUE THREAD

**Issue by jackychow** [okta/okta-sdk-python#144]
After including the okta sdk in my django project I got the following error:
```
Traceback (most recent call last):
  File "./manage.py", line 19, in <module>
    from configurations.management import execute_from_command_line
  File "/home/appuser/.local/lib/python3.8/site-packages/configurations/__init__.py", line 1, in <module>
    from .base import Configuration  # noqa
  File "/home/appuser/.local/lib/python3.8/site-packages/configurations/base.py", line 5, in <module>
    from django.conf import global_settings
  File "/home/appuser/.local/lib/python3.8/site-packages/django/conf/__init__.py", line 19, in <module>
    from django.core.validators import URLValidator
  File "/home/appuser/.local/lib/python3.8/site-packages/django/core/validators.py", line 8, in <module>
    from django.utils.encoding import punycode
  File "/home/appuser/.local/lib/python3.8/site-packages/django/utils/encoding.py", line 8, in <module>
    from django.utils.deprecation import RemovedInDjango40Warning
  File "/home/appuser/.local/lib/python3.8/site-packages/django/utils/deprecation.py", line 1, in <module>
    import asyncio
  File "/home/appuser/.local/lib/python3.8/site-packages/asyncio/__init__.py", line 21, in <module>
    from .base_events import *
  File "/home/appuser/.local/lib/python3.8/site-packages/asyncio/base_events.py", line 296
    future = tasks.async(future, loop=self)
                   ^
SyntaxError: invalid syntax
```

After some googling I think it's because the `asyncio` package is in conflict with what's already included in python core 3.8. Has anybody else run into the same problem?

Looks like `asyncio` should no longer be needed for python version beyond 3.3. 
https://pypi.org/project/asyncio/

is this here in order to support python versions even lower than 3.3?

**Comment by serhiibuniak-okta** [comment]
@jackychow Thank you for this detailed issue. Could you please, share a piece of code (and imports of course) where this error comes from? My first guess - **async** becomes a reserved word from Python 3.7. Also, it would be good if you can provide Django version, asyncio version and okta version.

**Comment by jackychow** [comment]
Hi thanks @serhiibuniak-okta 
Here are the versions for the packages:
django 3.1.3
asyncio 3.4.3 (latest - came from okta dependency)
okta 1.0.2

Thanks.

**Comment by serhiibuniak-okta** [comment]
Hi @jackychow , is there any possibility to take a look at code? At least small piece that can help me to reproduce the error?

**Comment by serhiibuniak-okta** [comment]
@jackychow I'm going to close this issue due to inactivity. Feel free to reopen this issue with any updates which can help in reproducing this error.
