### ISSUE TITLE
No error handing follows call to self._http_client.send_request in fire_request_helper

### ISSUE THREAD

**Issue by wsanchez** [okta/okta-sdk-python#173]
I'm getting this exception when I call `list_users()` on some of my Mac systems:

```console
    Traceback (most recent call last):
      File "/Users/wsanchez/Developer/profiles-tools/.tox/run/lib/python3.9/site-packages/twisted/internet/defer.py", line 460, in callback
        self._startRunCallbacks(result)
      File "/Users/wsanchez/Developer/profiles-tools/.tox/run/lib/python3.9/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
        self._runCallbacks()
      File "/Users/wsanchez/Developer/profiles-tools/.tox/run/lib/python3.9/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
        current.result = callback(current.result, *args, **kw)
      File "/Users/wsanchez/Developer/profiles-tools/.tox/run/lib/python3.9/site-packages/twisted/internet/defer.py", line 1475, in gotResult
        _inlineCallbacks(r, g, status)
    --- <exception caught here> ---
      File "/Users/wsanchez/Developer/profiles-tools/.tox/run/lib/python3.9/site-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks
        result = result.throwExceptionIntoGenerator(g)
      File "/Users/wsanchez/Developer/profiles-tools/.tox/run/lib/python3.9/site-packages/twisted/python/failure.py", line 512, in throwExceptionIntoGenerator
        return g.throw(self.type, self.value, self.tb)
      File "/Users/wsanchez/Developer/profiles-tools/.tox/run/lib/python3.9/site-packages/profiles/run/_tool.py", line 127, in run
        await _f(*args, **kwargs)
      File "/Users/wsanchez/Developer/profiles-tools/.tox/run/lib/python3.9/site-packages/profiles/run/_tool.py", line 456, in okta_find_users
        async for user in oktaClient.users():
      File "/Users/wsanchez/Developer/profiles-tools/.tox/run/lib/python3.9/site-packages/profiles/okta/_client.py", line 361, in users
        async for user in cast(
      File "/Users/wsanchez/Developer/profiles-tools/.tox/run/lib/python3.9/site-packages/profiles/okta/_client.py", line 104, in paginatedOktaRequest
        async for page in paginator():
      File "/Users/wsanchez/Developer/profiles-tools/.tox/run/lib/python3.9/site-packages/profiles/okta/_client.py", line 94, in paginator
        result, response = await _oktaRequest(coro)
      File "/Users/wsanchez/Developer/profiles-tools/.tox/run/lib/python3.9/site-packages/profiles/okta/_client.py", line 69, in _oktaRequest
        result, response, error = await futureAsDeferred(coro)
      File "/Users/wsanchez/Developer/profiles-tools/.tox/run/lib/python3.9/site-packages/twisted/internet/defer.py", line 824, in adapt
        extracted = result.result()
      File "/Users/wsanchez/Developer/profiles-tools/.tox/run/lib/python3.9/site-packages/okta/resource_clients/user_client.py", line 101, in list_users
        response, error = await self._request_executor\
      File "/Users/wsanchez/Developer/profiles-tools/.tox/run/lib/python3.9/site-packages/okta/request_executor.py", line 138, in execute
        _, response, response_body, error = await self.fire_request(request)
      File "/Users/wsanchez/Developer/profiles-tools/.tox/run/lib/python3.9/site-packages/okta/request_executor.py", line 175, in fire_request
        _, res_details, resp_body, error = await\
      File "/Users/wsanchez/Developer/profiles-tools/.tox/run/lib/python3.9/site-packages/okta/request_executor.py", line 223, in fire_request_helper
        check_429 = self.is_too_many_requests(res_details.status, resp_body)
    builtins.AttributeError: 'NoneType' object has no attribute 'status'
```

This is not happening on one of the three Macs I'm trying this on.

It appears that the call to `_, res_details, resp_body, error = await self._http_client.send_request(request)` right before then (lines 220-221) is resulting in an error, and there is no check in place here to catch this error.

Specifically, in the debugger I see that `res_details`, `resp_body` are both `None`, and if I print `error`, I get:
```python
ClientConnectorCertificateError(ConnectionKey(host='REDACTED', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)'))
```

If I print `request`, it is:
```python
{'method': 'GET', 'headers': {'User-Agent': 'okta-sdk-python/1.4.0 python/3.9.1 Darwin/20.3.0', 'Accept': 'application/json', 'Authorization': 'REDACTED', 'Content-Type': 'application/json'}, 'url': 'https://REDACTED/api/v1/users', 'data': {}}
```

So it seems like my problem is a TLS issue, which I will try to debug, but the SDK should be catching this error and doing something more useful than raising an unrelated `AttributeError`.

**Comment by wsanchez** [comment]
TLS issue resolved by running `sudo -H "/Applications/Python 3.9/Install Certificates.command"`

**Comment by bryanapellanes-okta** [comment]
@wsanchez,
Thanks for bringing this to our attention and I apologize for the inconvenience.  I will bring this to the attention of the python team to be addressed as appropriate.  Thanks for using Okta!

**Comment by serhiibuniak-okta** [comment]
@wsanchez Thanks for providing a lot of details, I'll take care of it. I will post updates here.

**Comment by serhiibuniak-okta** [comment]
@wsanchez Fix is merged to master and will be included into upcoming SDK release. Will keep you posted.

**Comment by serhiibuniak-okta** [comment]
@wsanchez SDK v1.4.1 released. I'm closing this issue as resolved. Feel free to reopen this issue if your problem still exists.

**Comment by wsanchez** [comment]
Great, thanks
