### ISSUE TITLE
Custom attributes are not listed in the profile unless it has a value populated once

### ISSUE THREAD

**Issue by sundarib-okta** [okta/okta-sdk-python#263]
Hi

I am having issues fetching custom attributes from user profile. I notice that only if the custom attribute
is updated with a value once, then it gets listed as an attribute in the profile.

My use case is to update a huge number of users with value for a custom attribute and before updating i need
to verify if the attribute has any value, but the attribute is not even seen in the profile if it was not previously updated with a value ? I would expect a None value for the custom attribute when it doesn't have a value.

Steps to reproduce

- Create a custom attribute via UI (Eg : brandIdentifier (String array))
![image](https://user-images.githubusercontent.com/88635477/145193901-094d70cc-5e49-4137-835c-04b1f32e2cf5.png)

- list users to view the profile

```
import asyncio
import logging
from okta.client import Client as OktaClient

config = {
    'orgUrl': 'https://XXXXXXX.oktapreview.com',
    'token': 'XXXXXXXXXXXXXXXX',
    "logging": {"enabled": True, "logLevel": logging.DEBUG}
}

async def main():

    query_parameters = {'search': 'profile.login eq "xxxx.xxx@obbb.com" or profile.login eq "mtest"'}

    client = OktaClient(config)
    users, resp, err = await client.list_users(query_parameters)
    for user in users:
        print(user)
loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

output has no brandIdentifier attribute in the profile

```
2021-12-08 21:12:58,342 - okta-sdk-python - http_client - DEBUG - Request: {'method': 'GET', 'headers': {'User-Agent': 'okta-sdk-python/2.3.1 python/3.9.9 Darwin/20.6.0', 'Accept': 'application/json', 'Authorization': 'SSWS XXXXXXXX'}, 'url': 'https://XXXXXXXX.oktapreview.com/api/v1/users/?search=profile.login+eq+%22XXXXXXXX.yyyyyyyy%40obbb.com%22+or+profile.login+eq+%22mtest%22', 'data': {}, 'form': {}}
{'embedded': None, 'links': None, 'activated': None, 'created': '2021-08-08T23:56:36.000Z', 'credentials': {'password': {'hash': None, 'hook': None, 'value': None}, 'provider': {'name': 'OKTA', 'type': <AuthenticationProviderType.OKTA: 'OKTA'>}, 'recovery_question': None}, 'id': '00u1r5ikefjTwMIvl0x7', 'last_login': '2021-12-08T08:14:10.000Z', 'last_updated': '2021-08-08T23:59:40.000Z', 'password_changed': '2021-08-08T23:59:40.000Z', 'profile': {'city': None, 'costCenter': None, 'countryCode': None, 'department': None, 'displayName': None, 'division': None, 'email': 'XXXXXXXX.yyyyyyyy@40obbb.com', 'employeeNumber': None, 'firstName': 'XXXXXXXX', 'honorificPrefix': None, 'honorificSuffix': None, 'lastName': 'yyyyyyyy', 'locale': None, 'login': 'XXXXXXXX.yyyyyyyy@okta.com', 'manager': None, 'managerId': None, 'middleName': None, 'mobilePhone': None, 'nickName': None, 'organization': None, 'postalAddress': None, 'preferredLanguage': None, 'primaryPhone': None, 'profileUrl': None, 'secondEmail': None, 'state': None, 'streetAddress': None, 'timezone': None, 'title': None, 'userType': None, 'zipCode': None}, 'status': <UserStatus.ACTIVE: 'ACTIVE'>, 'status_changed': '2021-08-08T23:59:40.000Z', 'transitioning_to_status': None, 'type': {'links': None, 'created': None, 'created_by': None, 'default': None, 'description': None, 'display_name': None, 'id': 'oty1r5ikbn6BPiFHi0x7', 'last_updated': None, 'last_updated_by': None, 'name': None}}
************************************************************
{'embedded': None, 'links': None, 'activated': '2021-11-30T01:52:22.000Z', 'created': '2021-11-30T01:52:21.000Z', 'credentials': {'password': {'hash': None, 'hook': None, 'value': None}, 'provider': {'name': 'OKTA', 'type': <AuthenticationProviderType.OKTA: 'OKTA'>}, 'recovery_question': None}, 'id': '00u3f76k3hq8ZpdvQ0x7', 'last_login': '2021-11-30T01:55:39.000Z', 'last_updated': '2021-12-08T09:19:47.000Z', 'password_changed': '2021-11-30T01:52:22.000Z', 'profile': {'city': None, 'costCenter': None, 'countryCode': None, 'department': None, 'displayName': None, 'division': None, 'email': 'XXXXXXXXdemo+4@gmail.com', 'employeeNumber': None, 'firstName': 'mfa', 'honorificPrefix': None, 'honorificSuffix': None, 'lastName': 'test', 'locale': None, 'login': 'mtest', 'manager': None, 'managerId': None, 'middleName': None, 'mobilePhone': None, 'nickName': 'Oktanut', 'organization': None, 'postalAddress': None, 'preferredLanguage': None, 'primaryPhone': None, 'profileUrl': None, 'secondEmail': None, 'state': None, 'streetAddress': None, 'timezone': None, 'title': None, 'userType': None, 'zipCode': None}, 'status': <UserStatus.ACTIVE: 'ACTIVE'>, 'status_changed': '2021-11-30T01:52:22.000Z', 'transitioning_to_status': None, 'type': {'links': None, 'created': None, 'created_by': None, 'default': None, 'description': None, 'display_name': None, 'id': 'oty1r5ikbn6BPiFHi0x7', 'last_updated': None, 'last_updated_by': None, 'name': None}}
************************************************************
```

- Add a line to the code as `print(user.profile.brandIdentifier)` or `print(user.profile.brand_identifier)` and notice error

```
Traceback (most recent call last):
  File "/Users/sundari/Work/scripts/user_tasks/ver2.py", line 44, in <module>
    loop.run_until_complete(main())
  File "/usr/local/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/sundari/Work/scripts/user_tasks/ver2.py", line 26, in main
    print(user.profile.brandIdentifier)
  File "/Users/sundari/.local/share/virtualenvs/user_tasks--HZL26ge/lib/python3.9/site-packages/okta/models/user_profile.py", line 224, in __getattr__
    raise AttributeError(f"'UserProfile' object has no attribute '{attr_name}'")
AttributeError: 'UserProfile' object has no attribute 'brandIdentifier'


  print(user.profile.brand_identifier)
  File "/Users/sundari/.local/share/virtualenvs/user_tasks--HZL26ge/lib/python3.9/site-packages/okta/models/user_profile.py", line 224, in __getattr__
    raise AttributeError(f"'UserProfile' object has no attribute '{attr_name}'")
AttributeError: 'UserProfile' object has no attribute 'brand_identifier'
```
- Referred [bug](https://github.com/okta/okta-sdk-python/issues/160)  - tried options listed here, adding a try block to print the custom attribute evaluates to the except block (ie no custom attribute)

- update the custom attribute for one of the user manually via UI and now query both the users again, the manually updated user profile would have `brandIdentifier` attribute but other user would not list this attribute (I would expect both users list the `brandIdentifier` attribute with one user having values and other user having `None` ? )

```
import asyncio
import logging
from okta.client import Client as OktaClient

config = {
    'orgUrl': 'https://XXXXXXX.oktapreview.com',
    'token': 'XXXXXXXXXXXXXXXX',
    "logging": {"enabled": True, "logLevel": logging.DEBUG}
}

async def main():

    query_parameters = {'search': 'profile.login eq "xxxx.xxx@obbb.com" or profile.login eq "mtest"'}

    client = OktaClient(config)
    users, resp, err = await client.list_users(query_parameters)
    for user in users:
        print(user)
        try:
            print(user.profile.brandIdentifier)
        except:
            print("No brand attr")
loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

```
2021-12-08 21:28:18,453 - okta-sdk-python - http_client - DEBUG - Request: {'method': 'GET', 'headers': {'User-Agent': 'okta-sdk-python/2.3.1 python/3.9.9 Darwin/20.6.0', 'Accept': 'application/json', 'Authorization': 'SSWS ffffffff'}, 'url': 'https://XXXXXX.oktapreview.com/api/v1/users/?search=profile.login+eq+%22XXXXXX.YYYYYYY%40okta.com%22+or+profile.login+eq+%22mtest%22', 'data': {}, 'form': {}}
{'embedded': None, 'links': None, 'activated': None, 'created': '2021-08-08T23:56:36.000Z', 'credentials': {'password': {'hash': None, 'hook': None, 'value': None}, 'provider': {'name': 'OKTA', 'type': <AuthenticationProviderType.OKTA: 'OKTA'>}, 'recovery_question': None}, 'id': '00u1r5ikefjTwMIvl0x7', 'last_login': '2021-12-08T08:14:10.000Z', 'last_updated': '2021-08-08T23:59:40.000Z', 'password_changed': '2021-08-08T23:59:40.000Z', 'profile': {'city': None, 'costCenter': None, 'countryCode': None, 'department': None, 'displayName': None, 'division': None, 'email': 'XXXXXX.YYYYYYY@40obbb.com', 'employeeNumber': None, 'firstName': 'XXXXXX', 'honorificPrefix': None, 'honorificSuffix': None, 'lastName': 'YYYYYYY', 'locale': None, 'login': 'XXXXXX.YYYYYYY@okta.com', 'manager': None, 'managerId': None, 'middleName': None, 'mobilePhone': None, 'nickName': None, 'organization': None, 'postalAddress': None, 'preferredLanguage': None, 'primaryPhone': None, 'profileUrl': None, 'secondEmail': None, 'state': None, 'streetAddress': None, 'timezone': None, 'title': None, 'userType': None, 'zipCode': None}, 'status': <UserStatus.ACTIVE: 'ACTIVE'>, 'status_changed': '2021-08-08T23:59:40.000Z', 'transitioning_to_status': None, 'type': {'links': None, 'created': None, 'created_by': None, 'default': None, 'description': None, 'display_name': None, 'id': 'oty1r5ikbn6BPiFHi0x7', 'last_updated': None, 'last_updated_by': None, 'name': None}}
No brand attr
************************************************************

{'embedded': None, 'links': None, 'activated': '2021-11-30T01:52:22.000Z', 'created': '2021-11-30T01:52:21.000Z', 'credentials': {'password': {'hash': None, 'hook': None, 'value': None}, 'provider': {'name': 'OKTA', 'type': <AuthenticationProviderType.OKTA: 'OKTA'>}, 'recovery_question': None}, 'id': '00u3f76k3hq8ZpdvQ0x7', 'last_login': '2021-11-30T01:55:39.000Z', 'last_updated': '2021-12-08T10:28:11.000Z', 'password_changed': '2021-11-30T01:52:22.000Z', 'profile': {'city': None, 'costCenter': None, 'countryCode': None, 'department': None, 'displayName': None, 'division': None, 'email': 'XXXXXXdemo+4@gmail.com', 'employeeNumber': None, 'firstName': 'mfa', 'honorificPrefix': None, 'honorificSuffix': None, 'lastName': 'test', 'locale': None, 'login': 'mtest', 'manager': None, 'managerId': None, 'middleName': None, 'mobilePhone': None, 'nickName': 'Oktanut', 'organization': None, 'postalAddress': None, 'preferredLanguage': None, 'primaryPhone': None, 'profileUrl': None, 'secondEmail': None, 'state': None, 'streetAddress': None, 'timezone': None, 'title': None, 'userType': None, 'zipCode': None, 'brandIdentifier': ['brand-abc']}, 'status': <UserStatus.ACTIVE: 'ACTIVE'>, 'status_changed': '2021-11-30T01:52:22.000Z', 'transitioning_to_status': None, 'type': {'links': None, 'created': None, 'created_by': None, 'default': None, 'description': None, 'display_name': None, 'id': 'oty1r5ikbn6BPiFHi0x7', 'last_updated': None, 'last_updated_by': None, 'name': None}}

['brand-abc']
************************************************************
```
- Remove the value from the profile which was updated manually and the attribute would show up as a none/empty array in my case

```
'primaryPhone': None, 'profileUrl': None, 'secondEmail': None, 'state': None, 'streetAddress': None, 'timezone': None, 'title': None, 'userType': None, 'zipCode': None, 'brandIdentifier': []}, 'status': <UserStatus.ACTIVE: 'ACTIVE'>, 'status_changed': '2021-11-30T01:52:22.000Z', 'transitioning_to_status': None, 'type': {'links': None, 'created': None, 'created_by': None, 'default': None, 'description': None, 'display_name': None, 'id': 'oty1r5ikbn6BPiFHi0x7', 'last_updated': None, 'last_updated_by': None, 'name': None}}
[]
************************************************************

It looks like if the custom attribute is not updated it won't show up as an attribute in the profile ?

**Comment by serhiibuniak-okta** [comment]
@sundarib-okta Thank you for providing a lot of details. Looking into it.

**Comment by serhiibuniak-okta** [comment]
@sundarib-okta I've got some info for you:
1) It is expected that schema properties with null or empty value do not show in the user profile in API. But they should be shown in the UI. You can use the schema API (https://developer.okta.com/docs/reference/api/schemas/) to list all properties in the schema if they want to cross check which properties are in the schema but not in user profile (because their values are null or empty).
2) ```update the custom attribute for one of the user manually via UI and now query both the users again, the manually updated user profile would have brandIdentifier attribute but other user would not list this attribute (I would expect both users list the brandIdentifier attribute with one user having values and other user having None ? )```
This is wrong expectation. Updating one user would only affect that user's profile. If they changed userA's custom property value from null to non-empty, that custom property will be displayed in userA's profile in API response. But userB's profile will still not include the custom property since the property value is still null for userB.

**Comment by sundarib-okta** [comment]
@serhiibuniak-okta 
1. Agreed, yes the attributes with null or empty value are not showing up in user profile API

Say below API call is not showing `nickName` for user in the profile attributes via API

![image](https://user-images.githubusercontent.com/88635477/145293971-2d8efef2-6dce-41d4-b8ad-902b24e20a0f.png)

when i query the same user via the SDK, i can fetch the value for nickName which would be `None`. 
```
async def main():
    
    query_parameters = {'search': 'profile.login eq "mtest2" or profile.login eq "mtest3"'}

    client = OktaClient(config)
    users, resp, err = await client.list_users(query_parameters)
    for user in users:
        print(user)
        print("*"*60)
        if (user.profile.nickName):
            print("User has a nickName as ", user.profile.nickName)
        else:
            print("Default nickName is ", user.profile.nickName)
```
```
{'embedded': None, 'links': None, 'activated': '2021-12-08T22:13:00.000Z', 'created': '2021-12-08T22:12:59.000Z', 'credentials': {'password': {'hash': None, 'hook': None, 'value': None}, 'provider': {'name': 'OKTA', 'type': <AuthenticationProviderType.OKTA: 'OKTA'>}, 'recovery_question': None}, 'id': '00u3guazbt0Kziwdq0x7', 'last_login': None, 'last_updated': '2021-12-08T22:13:00.000Z', 'password_changed': '2021-12-08T22:13:00.000Z', 'profile': {'city': None, 'costCenter': None, 'countryCode': None, 'department': None, 'displayName': None, 'division': None, 'email': 'mtest2@demo.com', 'employeeNumber': None, 'firstName': 'mtest2', 'honorificPrefix': None, 'honorificSuffix': None, 'lastName': 'mtest2', 'locale': None, 'login': 'mtest2', 'manager': None, 'managerId': None, 'middleName': None, 'mobilePhone': None, 'nickName': None, 'organization': None, 'postalAddress': None, 'preferredLanguage': None, 'primaryPhone': None, 'profileUrl': None, 'secondEmail': '', 'state': None, 'streetAddress': None, 'timezone': None, 'title': None, 'userType': None, 'zipCode': None}, 'status': <UserStatus.ACTIVE: 'ACTIVE'>, 'status_changed': '2021-12-08T22:13:00.000Z', 'transitioning_to_status': None, 'type': {'links': None, 'created': None, 'created_by': None, 'default': None, 'description': None, 'display_name': None, 'id': 'oty1r5ikbn6BPiFHi0x7', 'last_updated': None, 'last_updated_by': None, 'name': None}}
************************************************************
Default nickName is  None
``` 

Trying the same with a custom attribute would error as `AttributeError: 'UserProfile' object has no attribute 'brandIdentifier'`  instead of giving a `none` value

2. what i meant was like how we see all the basic profile attributes with values or as none in the returned user profile, the custom attributes are not showing up unless it had some updates made.

I guess base attributes are initialised with a default value of `None` where as custom attributes are not, maybe that is why the difference in behaviour.

**Comment by serhiibuniak-okta** [comment]
Yes, you're right with conclusion. Let me explain it a bit more.
1. The thing is, base attributes are "known" by SDK. So, even there is no value for such attribute in response, it knows how to deal with it, in our case SDK automatically assigns None: https://github.com/okta/okta-sdk-python/blob/master/okta/models/user_profile.py#L137-L168. 
2. Custom attributes can't be "known", thus SDK can't assign None to something it doesn't aware of. The only way how SDK get info about custom attributes - API responses.

**Comment by sundarib-okta** [comment]
@serhiibuniak-okta 
Thanks for the clarification

**Comment by serhiibuniak-okta** [comment]
@sundarib-okta Thank you for letting us know everything is clear and thanks for using OKTA!
